name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Show user
        run: whoami

      # 1. 檢出代碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 獲取提交的短哈希值
      - name: Extract short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      # 3. 編譯和打包 JAR 文件
      - name: Build JAR
        run: |
          ./gradlew bootJar --no-daemon

      # 4. 構建 Docker 鏡像
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ env.COMMIT_HASH }} .
          docker image ls -a

      # 5. 推送鏡像到 Docker Hub
      - name: Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ env.COMMIT_HASH }}

      # 6. 運行 Docker 容器
      - name: Run Docker Container
        run: |
          docker stop docker-hello || true
          docker rm docker-hello || true
          docker run -d --name docker-hello -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ env.COMMIT_HASH }}
